name: madminer
channels:
- pytorch
- anaconda
- defaults
dependencies:
- python=3.6.*
- matplotlib>=2.0.0
- numpy>=1.13.0
- h5py
- scipy>=1.0.0
- scikit-learn>=0.19.0
- pytorch>=1.0.0
- pytest
- pip
- pip:
  - uproot
  - scikit-hep>=0.5.0, <0.6.0
